version: "3.1"

services:
  mysql:
    image: mysql
    container_name: go-mysql
    ports:
      - 3306:3306
    volumes:
      - ~/Documents/Assets/data:/var/lib/mysql
    environment:
      MYSQL_USER: "user"
      MYSQL_PASSWORD: "password"
      MYSQL_ROOT_PASSWORD: password
  
volumes:
  mysql:
    driver: local
