# docker-compose.yml
version: '3.1'
#
services:
  redis:
    container_name: go_redis
    image: redis
    ports:
      - 6379:6379
    volumes:
      - go_redis_volume:/data
volumes:
  go_redis_volume:
    driver: local
# docker-compose.yml
