version: '3'

services:
  postgres:
    image: postgres
    container_name: pg_go
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=master
    networks:
      - psql
    ports:
      - "5432:5432"

networks:
  psql:
    driver: bridge
