
services:
  http:
    image: service_test
    environment:
      DATABASE_URL: "postgres://tester:testing@db:5432/music?sslmode=disable"
      PACT_TOKEN: "qjRvFT28GPdVZ3aeHMJtxw"
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    entrypoint:
      - "/bin/sh"
      - "-ecx"
      - |
        ./migrate -source file://migrations -database "$$DATABASE_URL" up &&
        /http-service

  db:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: tester
      POSTGRES_PASSWORD: testing
      POSTGRES_DB: music
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 3s
      retries: 3