version: v3
services:
  mongo-db:
    image: mongo
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
  redis:
    build:
      context: .
      dockerfile: Dockerfile.redis
    ports:
      - 6379:6379