// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package authors_repo

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Author struct {
	ID        int64
	Name      string
	Bio       pgtype.Text
	BirthYear int32
	Rating    int32
}

type Book struct {
	ID       int64
	Name     string
	Summary  pgtype.Text
	AuthorID pgtype.Int8
}
